name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up CML
        uses: iterative/setup-cml@v2

      - name: Install Dependencies
        run: make install

      - name: Code Formatting
        run: make format

      - name: Train Model
        run: make train

      - name: Evaluate Model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval

      - name: Update Branch with Results
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: make update-branch USER_NAME=$USER_NAME USER_EMAIL=$USER_EMAIL

  cd:
    name: Continuous Deployment
    needs: ci  # Runs only after CI is successful
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Hugging Face
        env:
          HF: ${{ secrets.HF }}
        run: make deploy HF=$HF
